import { shoot } from '../../audio/sfx/events';
import { GAME_W, SCRIPT_FPS } from '../../config';
import type { Entity } from '../../entities/Entity';
import { moveTo } from '../../script/patterns';
import { alignDoor, doorY, markWave, sideSpawnX, suspendRunning } from '../../script/stage';
import { EnemyBulletEntityKind, type EntityScript, HPEntityKind, type ScriptYield } from '../../script/types';
import { nextOrdinaryCoworkerSprite } from '../characters';
import { bullet } from '../kinds';

// Meeting-call intern — heartier than the opener intern. Drifts in,
// plants in the upper field, then shoots arrowhead-shaped formations of
// video cameras at the player (Zoom call, but make it surveillance)
// before dropping off the bottom. Each barrage launches a 4-3-2-1
// bowling-pin triangle row-by-row from the intern's position: the
// single-pin tip fires first and the back rows trail it by a row-gap
// in time, so the depth of the formation emerges from the launch
// cadence as the front row drifts ahead. All cameras share one
// velocity vector aimed at the player, so the arrow locks into shape
// once fully deployed and rolls in as a unit.

export const cameraBullet = new EnemyBulletEntityKind({
  sprite: 'cameraBullet',
  hitboxRadius: 5,
  hitboxShape: 'square',
});

const ENTRY_SPEED = 110;
const HOLD_FRAMES = 80;

// Four formations is what the 11s slot holds: the deepest-phase intern
// (phase 3, side-spawned, +30f stagger) clears the bottom edge at
// frame ~657 of 660. A fifth barrage pushes phase 3 past the slot end
// and `sweepStragglers` kills it mid-retreat. To raise pressure,
// tighten BARRAGE_GAP or HOLD_FRAMES instead of adding barrages.
const BARRAGES = 4;
// Stagger each intern's first barrage by `phase * BARRAGE_PHASE_STEP`
// frames so the four arrows don't fire in unison; the player gets a
// rolling drumbeat of incoming formations instead of one mass volley.
const BARRAGE_PHASE_STEP = 24;

// Bowling-pin triangle: 4 rows of 1-2-3-4 cameras, tip-forward. Row 0
// is the single-pin tip (fired first, so it ends up most forward); row
// 3 is the four-pin back row (fired last).
const ARROW_ROWS = 4;
const ROW_GAP = 18; // depth between adjacent rows (forward axis)
const PIN_GAP = 22; // horizontal spacing between pins within a row
const ARROW_SPEED = 105;
// Frames between successive row launches. Picked so each row trails
// the previous by exactly ROW_GAP at ARROW_SPEED — i.e. the bowling-
// pin depth is generated by the time delay between launches rather
// than by a forward offset at spawn.
const ROW_DELAY_FRAMES = Math.round((ROW_GAP / ARROW_SPEED) * SCRIPT_FPS);
// Lull between the last row of one barrage and the tip of the next.
// Sized so the formation-to-formation cycle (firing + gap) sits near
// the original 95-frame cadence; the random-shot subWaits below carve
// up this gap.
const BARRAGE_GAP = 65;

// Some interns sprinkle a couple of plain aimed bullets between camera
// barrages with a touch of angular jitter, so the formation rolls in
// over a steady rain of round bullets.
const RANDOM_SHOTS_PER_GAP = 3;
const RANDOM_JITTER = Math.PI / 8;
const RANDOM_SPEED = 173;

// Push past the player at well above PLAYER_SPEED so even the deepest-
// phase intern (last to start its exit thanks to BARRAGE_PHASE_STEP)
// clears the bottom edge before the wave's 11s slot ends.
const EXIT_SPEED = 320;

// Shoot one bowling-pin arrow out of the source: 1+2+3+4 = 10 cameras
// launched row-by-row from the intern's position, all sharing one
// velocity aimed at the player. The aim direction is captured once at
// the start of the burst so the rows fly in a single line even if the
// player drifts during the launch. Each camera is rotated to face along
// the aim vector so the lenses point at the player.
function* fireBowlingArrow(self: Entity): Generator<ScriptYield, void, void> {
  const aim = self.angleToPlayer();
  // Forward unit vector (direction of travel) and the perpendicular
  // sideways vector (90° CCW from forward).
  const fx = Math.cos(aim);
  const fy = Math.sin(aim);
  const sx = -fy;
  const sy = fx;
  const vx = fx * ARROW_SPEED;
  const vy = fy * ARROW_SPEED;
  for (let row = 0; row < ARROW_ROWS; row++) {
    if (row > 0) yield ROW_DELAY_FRAMES;
    shoot();
    const count = row + 1;
    for (let i = 0; i < count; i++) {
      // Centre each row's pins around s = 0: row k has k+1 pins at
      // s = (i - k/2) * PIN_GAP for i = 0..k. Pins spawn at the
      // source's current position with only a sideways offset; the
      // row's forward depth in the formation comes from the time
      // delay since the front row launched.
      const sideways = (i - row / 2) * PIN_GAP;
      const wx = self.x + sx * sideways;
      const wy = self.y + sy * sideways;
      const cam = self.spawn(cameraBullet, wx, wy, vx, vy);
      cam.setRotation(aim);
    }
  }
}

function fireRandomShot(self: Entity): void {
  shoot();
  const aim = self.angleToPlayer() + (Math.random() - 0.5) * 2 * RANDOM_JITTER;
  self.spawn(bullet, self.x, self.y, Math.cos(aim) * RANDOM_SPEED, Math.sin(aim) * RANDOM_SPEED);
}

function makeMeetingInternScript(targetX: number, targetY: number, phase: number, shootsRandom: boolean): EntityScript {
  return function* (self: Entity) {
    yield* moveTo(self, targetX, targetY, ENTRY_SPEED);
    if (phase === 0) self.say("You're on camera!", HOLD_FRAMES);
    yield HOLD_FRAMES + phase * BARRAGE_PHASE_STEP;

    // Slice each gap into RANDOM_SHOTS_PER_GAP + 1 sub-waits so random
    // shots land at evenly spaced moments inside the lull between camera
    // formations rather than all at once.
    const subWait = Math.floor(BARRAGE_GAP / (RANDOM_SHOTS_PER_GAP + 1));
    for (let i = 0; i < BARRAGES; i++) {
      yield* fireBowlingArrow(self);
      // After the last formation, head straight for the front rather than
      // serving out the inter-barrage random shots and gap.
      if (i === BARRAGES - 1) break;
      let consumed = 0;
      for (let r = 0; r < RANDOM_SHOTS_PER_GAP; r++) {
        yield subWait;
        consumed += subWait;
        if (shootsRandom) fireRandomShot(self);
      }
      yield BARRAGE_GAP - consumed;
    }

    // Push through the front: down past the player, off the bottom.
    self.setVelocity(0, EXIT_SPEED);
  };
}

// `sprite` is just the default if no spawn override is passed; the
// wave below always passes `nextOrdinaryCoworkerSprite` so the four
// interns are drawn from the seeded coworker pool.
export const meetingIntern = new HPEntityKind({
  sprite: 'whiteFemale1',
  hitboxRadius: 16,
  hp: 30,
  damageClass: ['player'],
  damagedByClass: ['enemy'],
});

// Four interns converge: two from the top, one from each side, planting
// at the corners of an upper-band rectangle so their arrows roll in down
// overlapping lanes. Phase rotates around the four so each arrow lands
// on its own beat instead of arriving simultaneously. The two side
// entries route through whichever door is closest to SIDE_Y, with a
// pre-suspend `alignDoor` snapping a panel into that band so the design
// y holds.
const MEETING_SIDE_Y = 220;
export function* meetingInternsWave(self: Entity): Generator<ScriptYield, void, void> {
  markWave(self, 'meeting interns');
  self.stage.scheduleMultDrop('regular');
  yield* alignDoor(self, MEETING_SIDE_Y);
  yield* suspendRunning(self, function* () {
    const TOP_Y = 110;
    const SIDE_INSET = 80;
    const sideY = doorY(self, MEETING_SIDE_Y);
    // Phases 1 and 3 (one top, one side) sprinkle plain aimed bullets
    // between their camera barrages so the encounter isn't a pure
    // formation-dodge — there's always a stray round to track.
    // TODO(shmup-design): each pair below currently spawns on the same
    // frame. Per "Bullet Hell Shmup Design 101", two high-HP enemies
    // appearing simultaneously force a snap triage decision the player
    // can't reason about. Consider staggering each pair by ~0.4s so one
    // enters, then the other — keeping the formation but making it
    // readable. Skipped for now: balance / playtest implications.
    self.spawn(meetingIntern, GAME_W * 0.3, -30, 0, 0, {
      script: makeMeetingInternScript(GAME_W * 0.3, TOP_Y, 0, false),
      sprite: nextOrdinaryCoworkerSprite(self.stage),
    });
    self.spawn(meetingIntern, GAME_W * 0.7, -30, 0, 0, {
      script: makeMeetingInternScript(GAME_W * 0.7, TOP_Y, 1, true),
      sprite: nextOrdinaryCoworkerSprite(self.stage),
    });
    yield 30;
    self.spawn(meetingIntern, sideSpawnX(-1), sideY, 0, 0, {
      script: makeMeetingInternScript(SIDE_INSET, sideY, 2, false),
      sprite: nextOrdinaryCoworkerSprite(self.stage),
    });
    self.spawn(meetingIntern, sideSpawnX(1), sideY, 0, 0, {
      script: makeMeetingInternScript(GAME_W - SIDE_INSET, sideY, 3, true),
      sprite: nextOrdinaryCoworkerSprite(self.stage),
    });
  });
}
